export const FALLBACK_DOCTORS = [
  // ── Daimi heyət ──
  {
    id: "fallback-perm-1",
    name: "Dr. Əfqan Abdullayev",
    specialty_az: "Dermatoloq-Venerologiya",
    specialty_ru: "Дерматовенерология",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/dermatovenerolog.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-2",
    name: "Dr. Firdovsi Məmmədov",
    specialty_az: "Kardioloq",
    specialty_ru: "Кардиолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/kardioloq.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-3",
    name: "Dr. Cəlal Hüseynov",
    specialty_az: "Nevropatoloq",
    specialty_ru: "Невропатолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/nevropatoloq.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-4",
    name: "Dr. Elgiz Kazımov",
    specialty_az: "Pediatr",
    specialty_ru: "Педиатр",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/pediatr.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-5",
    name: "Aygül Nəcəfova",
    specialty_az: "Psixoloq",
    specialty_ru: "Психолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/psixoloq.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-6",
    name: "Fərid İsazadə",
    specialty_az: "Texniki Reabilitoloq",
    specialty_ru: "Технический реабилитолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/texnikreabilitoloq.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  {
    id: "fallback-perm-7",
    name: "Dr. Müjgan Ələsgərli",
    specialty_az: "Fizioterapevt",
    specialty_ru: "Физиотерапевт",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/uzmanfizioterapevt.jpg.jpeg",
    is_guest: false,
    is_featured_this_week: false,
    visit_date: null,
  },
  // ── Davetli həkimlər ──
  {
    id: "fallback-guest-1",
    name: "Dr. Xədicə Salmanova",
    specialty_az: "Ginekoloq-USM",
    specialty_ru: "Гинеколог-УЗИ",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetliginekologuzist.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: true,
    visit_date: "18 Yanvar",
  },
  {
    id: "fallback-guest-2",
    name: "Dr. Turan Musayeva",
    specialty_az: "Nevropatoloq",
    specialty_ru: "Невропатолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetlinevropotoloq.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: true,
    visit_date: "25 Yanvar",
  },
  {
    id: "fallback-guest-3",
    name: "Dr. Sənan Aşirov",
    specialty_az: "Ortoped-Travmatoloq",
    specialty_ru: "Ортопед-Травматолог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetliortopedtravmatoloq.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: true,
    visit_date: "25 Yanvar",
  },
  {
    id: "fallback-guest-4",
    name: "Dr. Kənan Qarayev",
    specialty_az: "Pediatr",
    specialty_ru: "Педиатр",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetlipediatr.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: false,
    visit_date: "26 Aprel",
  },
  {
    id: "fallback-guest-5",
    name: "Dr. Bəxtiyar Mustafayev",
    specialty_az: "Psixoterapevt",
    specialty_ru: "Психотерапевт",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetlipsixoterapevt.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: false,
    visit_date: "06 Yanvar",
  },
  {
    id: "fallback-guest-6",
    name: "Dr. Gülnarə Xasıyeva",
    specialty_az: "Oftalmologiya",
    specialty_ru: "Офтальмология",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetliT.E.Noftalmoloq.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: false,
    visit_date: "04 Fevral",
  },
  {
    id: "fallback-guest-7",
    name: "Dr. Qardaşxan Mamedov",
    specialty_az: "Uroloq-Androloq",
    specialty_ru: "Уролог-Андролог",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetliuroloq-androloq.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: false,
    visit_date: "25 Yanvar",
  },
  {
    id: "fallback-guest-8",
    name: "Dr. Ruslan Gözəlov",
    specialty_az: "USM Həkimi",
    specialty_ru: "Врач УЗИ",
    bio_az: "",
    bio_ru: "",
    image_url: "/images/doctors/devetliUSMhekim.jpg.jpeg",
    is_guest: true,
    is_featured_this_week: true,
    visit_date: "26 Aprel",
  },
];

export const FALLBACK_SERVICES = [
  // Daimi xidmətlər
  { id: "fallback-svc-1",  title_az: "USM müayinə",                              title_ru: "УЗИ обследование",                        description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-2",  title_az: "Fizioterapiya",                             title_ru: "Физиотерапия",                            description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-3",  title_az: "Pediatrik müayinə",                         title_ru: "Педиатрический осмотр",                   description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-4",  title_az: "Kardiologiya xidməti (Exo, EKQ)",           title_ru: "Кардиология (ЭхоКГ, ЭКГ)",               description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-5",  title_az: "Elektroensefaloqrafiya (EEQ)",              title_ru: "Электроэнцефалография (ЭЭГ)",             description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-6",  title_az: "Nevroloji xidmət",                          title_ru: "Неврологические услуги",                  description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-7",  title_az: "Dermatologiya",                             title_ru: "Дерматология",                            description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-8",  title_az: "Rentgenoloji xidmət",                       title_ru: "Рентгенологические услуги",               description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-9",  title_az: "Laboratoriya xidməti (hər növ analizlər)", title_ru: "Лабораторные услуги (все виды анализов)", description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-10", title_az: "Ginekologiya",                              title_ru: "Гинекология",                             description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-11", title_az: "Terapevtik xidmət",                         title_ru: "Терапевтические услуги",                  description_az: null, description_ru: null, is_guest_service: false },
  { id: "fallback-svc-12", title_az: "Uşaqlar üçün psixoloq xidməti",            title_ru: "Услуги психолога для детей",              description_az: null, description_ru: null, is_guest_service: false },
  // Qonaq həkim xidmətləri
  { id: "fallback-svc-13", title_az: "Psixoterapevtik xidmət",                    title_ru: "Психотерапевтические услуги",             description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-14", title_az: "Göz həkimi",                                title_ru: "Офтальмолог",                             description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-15", title_az: "Travmatoloji-ortopedik",                    title_ru: "Травматология-ортопедия",                 description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-16", title_az: "Nevroloji",                                 title_ru: "Неврология",                              description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-17", title_az: "Pediatrik",                                 title_ru: "Педиатрия",                               description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-18", title_az: "Uroloq - Androloq",                         title_ru: "Уролог - Андролог",                       description_az: null, description_ru: null, is_guest_service: true },
  { id: "fallback-svc-19", title_az: "Endokrinoloji xidmət",                      title_ru: "Эндокринология",                          description_az: null, description_ru: null, is_guest_service: true },
];
