export const FALLBACK_DOCTORS = [
  {
    id: "fallback-1",
    name: "Dr. Leyla Məmmədova",
    specialty_az: "Kardioloq",
    specialty_ru: "Кардиолог",
    bio_az: "15 illik təcrübəyə malik kardioloq. Ürək-damar xəstəliklərinin diaqnostikası və müalicəsi üzrə mütəxəssis.",
    bio_ru: "Кардиолог с 15-летним стажем. Специалист по диагностике и лечению сердечно-сосудистых заболеваний.",
    image_url: null,
    is_guest: true,
    is_featured_this_week: true,
  },
  {
    id: "fallback-2",
    name: "Dr. Rauf Hüseynov",
    specialty_az: "Nevroloq",
    specialty_ru: "Невролог",
    bio_az: "Nevrologiya sahəsində 12 il təcrübəsi olan mütəxəssis. Baş ağrıları, osteoxondroz və sinir sistemi xəstəliklərini müalicə edir.",
    bio_ru: "Специалист с 12 годами опыта в неврологии. Лечит головные боли, остеохондроз и заболевания нервной системы.",
    image_url: null,
    is_guest: true,
    is_featured_this_week: true,
  },
  {
    id: "fallback-3",
    name: "Dr. Günel Əliyeva",
    specialty_az: "Endokrinoloq",
    specialty_ru: "Эндокринолог",
    bio_az: "Endokrin sistemi xəstəlikləri üzrə mütəxəssis. Diabet, tiroid xəstəlikləri və hormonal pozğunluqların müalicəsini həyata keçirir.",
    bio_ru: "Специалист по заболеваниям эндокринной системы. Лечит диабет, болезни щитовидной железы и гормональные нарушения.",
    image_url: null,
    is_guest: true,
    is_featured_this_week: true,
  },
];

export const FALLBACK_SERVICES = [
  {
    id: "fallback-svc-1",
    title_az: "Kardioloji yoxlama",
    title_ru: "Кардиологическое обследование",
    description_az: "EKQ, exokardioqrafiya və ürək-damar sistemininin tam diaqnostikası.",
    description_ru: "ЭКГ, эхокардиография и полная диагностика сердечно-сосудистой системы.",
  },
  {
    id: "fallback-svc-2",
    title_az: "Nevroloji konsultasiya",
    title_ru: "Неврологическая консультация",
    description_az: "Sinir sistemi xəstəliklərinin diaqnostikası, baş ağrıları və osteoxondroz müalicəsi.",
    description_ru: "Диагностика заболеваний нервной системы, лечение головных болей и остеохондроза.",
  },
  {
    id: "fallback-svc-3",
    title_az: "Endokrinologiya",
    title_ru: "Эндокринология",
    description_az: "Diabet, tiroid xəstəlikləri və metabolik pozğunluqların müayinəsi və müalicəsi.",
    description_ru: "Обследование и лечение диабета, болезней щитовидной железы и метаболических нарушений.",
  },
  {
    id: "fallback-svc-4",
    title_az: "Laborator analizlər",
    title_ru: "Лабораторные анализы",
    description_az: "Qan, sidik və digər analizlərin sürətli və dəqiq nəticələrlə aparılması.",
    description_ru: "Проведение анализов крови, мочи и других исследований с быстрыми и точными результатами.",
  },
  {
    id: "fallback-svc-5",
    title_az: "UZI diaqnostikası",
    title_ru: "УЗИ диагностика",
    description_az: "Daxili orqanların, qalxanabənzər vəzinin və damarların ultrasəs müayinəsi.",
    description_ru: "Ультразвуковое исследование внутренних органов, щитовидной железы и сосудов.",
  },
  {
    id: "fallback-svc-6",
    title_az: "Ümumi terapevt",
    title_ru: "Общая терапия",
    description_az: "İlkin müayinə, xəstəliklərin qarşısının alınması və müvafiq mütəxəssislərə yönləndirilmə.",
    description_ru: "Первичный осмотр, профилактика заболеваний и направление к профильным специалистам.",
  },
];
