// lib/pricing-data.ts
// VitaLife Klinika — laboratoriya qiymət siyahısı (mənbə: klinikanın PRAYS sənədi).
// price null => UI-də 'Qiymət üçün soruşun' göstərilir.

export type PriceItem = { name_az: string; price: string | null };
export type PriceCategory = { title_az: string; title_ru: string; items: PriceItem[] };

export const priceList: PriceCategory[] = [
  {
    title_az: "Ümumi analizlər",
    title_ru: "Общие анализы",
    items: [
      { name_az: "Qanın ümumi analizi (leykoformula)", price: "10 ₼" },
      { name_az: "Sidiyin ümumi analizi", price: "5 ₼" },
      { name_az: "Şəkərin ümumi analizi (damardan)", price: "4 ₼" },
      { name_az: "Laxtalanma", price: "3 ₼" },
      { name_az: "Qan qrupu", price: "6 ₼" },
    ],
  },
  {
    title_az: "Kardioloji və funksional müayinə",
    title_ru: "Кардиологические и функциональные исследования",
    items: [
      { name_az: "EKQ", price: "10 ₼" },
      { name_az: "EXO-ürək", price: "35 ₼" },
      { name_az: "Kompüter Ensefaloqrafiyası", price: "30 ₼" },
      { name_az: "Troponinlərin təyini", price: "20 ₼" },
      { name_az: "NT PRO BNP", price: "45 ₼" },
      { name_az: "Kreatin kinaza (CK)", price: "12 ₼" },
      { name_az: "D. Dimer", price: "15 ₼" },
    ],
  },
  {
    title_az: "USM (Ultrasəs müayinə)",
    title_ru: "УЗИ (ультразвуковое исследование)",
    items: [
      { name_az: "Tək orqan USM", price: "20 ₼" },
      { name_az: "Qarın boşluğu USM", price: "30 ₼" },
      { name_az: "Ginekoloji USM", price: "30 ₼" },
      { name_az: "Süd vəzisi USM", price: "20 ₼" },
      { name_az: "Qalxanvari vəz USM", price: "20 ₼" },
    ],
  },
  {
    title_az: "Rentgen və fizioterapiya",
    title_ru: "Рентген и физиотерапия",
    items: [
      { name_az: "Rentgen", price: "25 ₼" },
      { name_az: "Elektroforez", price: "10 ₼" },
      { name_az: "Maqnit", price: "10 ₼" },
      { name_az: "Lazer", price: "10 ₼" },
    ],
  },
  {
    title_az: "Hormonal müayinələr",
    title_ru: "Гормональные исследования",
    items: [
      { name_az: "TSH (tireostimullaşdırıcı hormon)", price: "14 ₼" },
      { name_az: "T3", price: "14 ₼" },
      { name_az: "T4", price: "14 ₼" },
      { name_az: "Anti TPO", price: "15 ₼" },
      { name_az: "Anti Tq", price: "15 ₼" },
      { name_az: "Estradiol", price: "14 ₼" },
      { name_az: "Prolaktin", price: "14 ₼" },
      { name_az: "LH", price: "14 ₼" },
      { name_az: "FSH", price: "14 ₼" },
      { name_az: "Progesteron", price: "15 ₼" },
      { name_az: "Testosteron (sərbəst)", price: "15 ₼" },
      { name_az: "Testosteron (ümumi)", price: "15 ₼" },
      { name_az: "Kortizol", price: "20 ₼" },
      { name_az: "DHEAS", price: "15 ₼" },
      { name_az: "AKTH hormonu", price: "30 ₼" },
      { name_az: "İGF-1", price: "40 ₼" },
      { name_az: "Qanda insulinin təyini", price: "20 ₼" },
      { name_az: "C-PEPTİDE", price: "12 ₼" },
      { name_az: "Qlikohemoqlobinin təyini", price: "20 ₼" },
      { name_az: "Xorionik qonadotropin (XQ)", price: "20 ₼" },
    ],
  },
  {
    title_az: "Biokimyəvi müayinələr",
    title_ru: "Биохимические исследования",
    items: [
      { name_az: "Bilirubin", price: "6 ₼" },
      { name_az: "Aspartataminotransferaza (AST)", price: "6 ₼" },
      { name_az: "Alaninaminotransferaza (ALT)", price: "6 ₼" },
      { name_az: "Qammaqlutamiltransferaza (QQT)", price: "6 ₼" },
      { name_az: "Kreatin", price: "6 ₼" },
      { name_az: "Amilaza", price: "6 ₼" },
      { name_az: "Sidik turşusu", price: "6 ₼" },
      { name_az: "Diastaza", price: "6 ₼" },
      { name_az: "Albumin", price: "6 ₼" },
      { name_az: "Qələvi fosfataza (ALP)", price: "6 ₼" },
      { name_az: "Xolesterin", price: "6 ₼" },
      { name_az: "Zülal (ümumi)", price: "6 ₼" },
      { name_az: "Triqliserid", price: "6 ₼" },
      { name_az: "Qalıq azotu", price: "6 ₼" },
      { name_az: "Sidik cövhəri", price: "6 ₼" },
      { name_az: "Maqnezium (Mg)", price: "6 ₼" },
      { name_az: "Fosfor", price: "6 ₼" },
      { name_az: "Ferrum (FE)", price: "6 ₼" },
      { name_az: "Kalsium (CA)", price: "6 ₼" },
      { name_az: "Vitamin D", price: "35 ₼" },
      { name_az: "Lipid spektrinin təyini (xolesterin, triqliserid, HDL, LDL)", price: "15 ₼" },
      { name_az: "Ferritin", price: "20 ₼" },
    ],
  },
  {
    title_az: "İnfeksiya analizləri",
    title_ru: "Анализы на инфекции",
    items: [
      { name_az: "Hepatit C ANTİ-HCV test", price: "6 ₼" },
      { name_az: "Hepatit B HbsAg test", price: "6 ₼" },
      { name_az: "Anti-HCV (IFA) G, M", price: "12 ₼" },
      { name_az: "Anti-HBsAG (İFA)", price: "12 ₼" },
      { name_az: "AİDS-QİÇS (kart test)", price: "6 ₼" },
      { name_az: "RW-Syphilis (kart test, VRDL)", price: "6 ₼" },
      { name_az: "RW-Syphilis (ifa) M", price: "20 ₼" },
      { name_az: "H.PYLORİ Ab təyini (helikobakteriya)", price: "18 ₼" },
      { name_az: "Ureplazma, Mikoplazma (antibiotiklərə həssaslıqla)", price: "30 ₼" },
      { name_az: "Bruselyoz M, G (hər biri)", price: "15 ₼" },
    ],
  },
  {
    title_az: "İmmunoloji və romatoloji analizlər",
    title_ru: "Иммунологические и ревматологические анализы",
    items: [
      { name_az: "ASO", price: "10 ₼" },
      { name_az: "CRP", price: "10 ₼" },
      { name_az: "CRP (seleksion, rəqəmlə)", price: "12 ₼" },
      { name_az: "RF (rəqəmsal)", price: "10 ₼" },
      { name_az: "ANTİ CCP", price: "30 ₼" },
      { name_az: "Immunoglobulin IgE", price: "18 ₼" },
      { name_az: "Kardiolipin G", price: "15 ₼" },
      { name_az: "Kardiolipin M", price: "15 ₼" },
      { name_az: "Toxuma Transqlutaminaza", price: "30 ₼" },
      { name_az: "Ana skrin G", price: "15 ₼" },
      { name_az: "Koaquloqramma (İNR, Prot. indeks, Prot. zamanı)", price: "12 ₼" },
    ],
  },
  {
    title_az: "Onkomarkerlər",
    title_ru: "Онкомаркеры",
    items: [
      { name_az: "Yumurtalıqların onkomarkeri (CA125)", price: "25 ₼" },
      { name_az: "PSA (prostat-spesifik antigen)", price: "25 ₼" },
      { name_az: "CEA (bəd xassəli şişlərin təyini)", price: "25 ₼" },
      { name_az: "AFP (qaraciyər şişi / hamiləlikdə dölün təyini)", price: "25 ₼" },
    ],
  },
  {
    title_az: "TORCH və hamiləlik infeksiyaları",
    title_ru: "TORCH и инфекции при беременности",
    items: [
      { name_az: "Toxoplasma İgM", price: "12 ₼" },
      { name_az: "Toxoplasma İgG", price: "12 ₼" },
      { name_az: "Herpes İgM", price: "12 ₼" },
      { name_az: "Herpes İgG", price: "12 ₼" },
      { name_az: "Herpes simplex (yaxmada)", price: "12 ₼" },
      { name_az: "Cytomeqalovirus İgM", price: "12 ₼" },
      { name_az: "Cytomeqalovirus İgG", price: "12 ₼" },
      { name_az: "Cytomeqalovirus (yaxmada)", price: "11 ₼" },
      { name_az: "Chlamydia İgM", price: "14 ₼" },
      { name_az: "Chlamydia İgG", price: "14 ₼" },
      { name_az: "Chlamydia (yaxmada)", price: "11 ₼" },
      { name_az: "Rubella İgM", price: "12 ₼" },
      { name_az: "Rubella İgG", price: "12 ₼" },
    ],
  },
  {
    title_az: "Parazitoloji müayinələr",
    title_ru: "Паразитологические исследования",
    items: [
      { name_az: "Lamblia intestinalis igG (M)", price: "12 ₼" },
      { name_az: "Nəcisdə lumbricoides təyini", price: "12 ₼" },
      { name_az: "Göbələyin təyini", price: "10 ₼" },
      { name_az: "Skabioz təyini", price: "10 ₼" },
      { name_az: "Demodex", price: "10 ₼" },
    ],
  },
  {
    title_az: "Digər analizlər",
    title_ru: "Прочие анализы",
    items: [
      { name_az: "Spermoqramma", price: "20 ₼" },
      { name_az: "Hemoqlobin elektroforezi", price: "40 ₼" },
    ],
  },
];